# III. Introduction to Matrices

Let's create a simple 4x4 matrix:

In [1]:
A = [1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16]


A =

     1     2     3     4
     5     6     7     8
     9    10    11    12
    13    14    15    16



When creating a matrix, each row of a matrix is its elements separated by spaces; and then the rows themselves are separated by __;__.

If you wanted the diagonal elements of A you would use the *diag* command:

In [2]:
diag(A)


ans =

     1
     6
    11
    16



Matlab has built-in commands for creating many commonly used matrices. We can create a 2x2 matrix of zeros:

In [3]:
zeros(2)


ans =

     0     0
     0     0



Or a 3x4 matrix of ones:

In [4]:
ones(3,4)


ans =

     1     1     1     1
     1     1     1     1
     1     1     1     1



To create the identity matrix use the *eye* command:

In [5]:
eye(4)


ans =

     1     0     0     0
     0     1     0     0
     0     0     1     0
     0     0     0     1



To create a diagonal matrix:

In [6]:
diag([1 3 5])


ans =

     1     0     0
     0     3     0
     0     0     5



A random 3x3matrix where each element is uniformly distributed between 0 and 1:

In [7]:
rand(3)


ans =

    0.8147    0.9134    0.2785
    0.9058    0.6324    0.5469
    0.1270    0.0975    0.9575



A common operation is to create matrices using other matrices. Matrices can be constructed in block form. Here we create a matrix __result__ using the matrices __B__, __C__, __D__, and __E__:

In [8]:
B = [2 2;2 2];
C = eye(2);
D = ones(2);
E = [3 3;3 3];

result = [B C; D E]


result =

     2     2     1     0
     2     2     0     1
     1     1     3     3
     1     1     3     3



The *repmat* function is very useful Matlab built-in used to construct tiled block matrices.

In [9]:
repmat(result,3,2)


ans =

     2     2     1     0     2     2     1     0
     2     2     0     1     2     2     0     1
     1     1     3     3     1     1     3     3
     1     1     3     3     1     1     3     3
     2     2     1     0     2     2     1     0
     2     2     0     1     2     2     0     1
     1     1     3     3     1     1     3     3
     1     1     3     3     1     1     3     3
     2     2     1     0     2     2     1     0
     2     2     0     1     2     2     0     1
     1     1     3     3     1     1     3     3
     1     1     3     3     1     1     3     3



### Indexing Into Matrices

A common need is the ability to index into a matrix and extract parts of the matrix (i.e. a submatrix). In Matlab indexing into a matrix is accomplished using parentheses. Let's consider our matrix __result__:

Suppose we want to extract the upper left matrix of 2s and assign it to a new variable called __subupper__. Indexing starts at 1 and we'd simply specify the range of rows and columns desired. Here we want rows 1 through 2 and columns 1 through 2:

In [10]:
subupper = result(1:2, 1:2)


subupper =

     2     2
     2     2



If we wanted the middle two rows but only columns 1 through 3:

In [11]:
midrows = result(2:3, 1:3)


midrows =

     2     2     0
     1     1     3



What if we wanted the first two columns?

In [12]:
firstcols = result(1:4,1:2)


firstcols =

     2     2
     2     2
     1     1
     1     1



Another way to do the same thing using the "end" keyword:

In [13]:
firstcols = result(1:end, 1:2)


firstcols =

     2     2
     2     2
     1     1
     1     1



You can use the colon ":" notation to get the entire range of the dimension of interest:

In [14]:
result(:,3)


ans =

     1
     0
     3
     3



Above we asked for all the rows and just the third column of the matrix __result__.

You can be specific about what you want. What if you wanted just the corner numbers?

In [15]:
result([1 end], [1 end])


ans =

     2     0
     1     3



### Memory Layout of Matrices

You can also think of a matrix as being stored as a single long array with the first column being stacked on top of the second column, the second column on top of the third column, etc. This approach to storing multidimensional arrays is referred to as __column-major order__.

So you can also index into the matrix using a single index instead of specifying the row and column indices. Let's see how this works using the matrix A we created above.

In [16]:
A


A =

     1     2     3     4
     5     6     7     8
     9    10    11    12
    13    14    15    16



In [17]:
A(:)


ans =

     1
     5
     9
    13
     2
     6
    10
    14
     3
     7
    11
    15
     4
     8
    12
    16



The index count starts at one as before. So, here __A(1)__ is 1, __A(2)__ is 5, __A(7)__ is 10, etc. There are 16 total elements in __A__ so the last element __A(16)__ is 16.

In [18]:
A(7)


ans =

    10



We saw the ":" notation before and how it's used to specify a range of numbers, i.e. 1:3. This syntax is often used in Matlab to create vectors. __begin:stride:end__ is the general syntax and by default __stride__ has a value of 1 (i.e. if not specified):

In [19]:
a = 1:10


a =

     1     2     3     4     5     6     7     8     9    10



If you wanted to go from 3 to 8 in increments of 0.5 you can specify a stride of 0.5:

In [20]:
b = 3:0.5:8


b =

  Columns 1 through 7

    3.0000    3.5000    4.0000    4.5000    5.0000    5.5000    6.0000

  Columns 8 through 11

    6.5000    7.0000    7.5000    8.0000



Or if you wanted a sequence to start at -20 and go to 1 in increments of 1.3:

In [21]:
c = -20:1.3:1


c =

  Columns 1 through 7

  -20.0000  -18.7000  -17.4000  -16.1000  -14.8000  -13.5000  -12.2000

  Columns 8 through 14

  -10.9000   -9.6000   -8.3000   -7.0000   -5.7000   -4.4000   -3.1000

  Columns 15 through 17

   -1.8000   -0.5000    0.8000



Notice Matlab could not reach all the way to 1 using the specified increment of 1.3; so it went up in increments of 1.3 until it reached as close to 1 without going beyond 1.

The linspace command will create n equally spaced points between a and b, *linspace(__a__,__b__,__n__)*:

In [22]:
linspace(1.5, 5.5, 10)


ans =

  Columns 1 through 7

    1.5000    1.9444    2.3889    2.8333    3.2778    3.7222    4.1667

  Columns 8 through 10

    4.6111    5.0556    5.5000



Before moving on to basic operations with matrices I'll mention that you can create large (i.e., more than two ) dimenional arrays in Matlab as well. For example, the following creates a 4x3x3 random matrix:

In [23]:
F = randn(4, 3, 3)


F(:,:,1) =

    2.7694   -0.0631    1.4897
   -1.3499    0.7147    1.4090
    3.0349   -0.2050    1.4172
    0.7254   -0.1241    0.6715


F(:,:,2) =

   -1.2075    1.0347   -0.7873
    0.7172    0.7269    0.8884
    1.6302   -0.3034   -1.1471
    0.4889    0.2939   -1.0689


F(:,:,3) =

   -0.8095   -0.7549   -0.2414
   -2.9443    1.3703    0.3192
    1.4384   -1.7115    0.3129
    0.3252   -0.1022   -0.8649



You can think of this as 3 "layers" of individual 4x3 matrices (i.e. a cube), i.e. each layer is a 4x3 matrix. You can index into multidementional arrays as well:

In [24]:
G = F(1:2, 2:3, :)


G(:,:,1) =

   -0.0631    1.4897
    0.7147    1.4090


G(:,:,2) =

    1.0347   -0.7873
    0.7269    0.8884


G(:,:,3) =

   -0.7549   -0.2414
    1.3703    0.3192



Above, we specified columns 2 through 3 of the first two rows from all the layers.

You can do many of the common matrix operations in Matlab. I'm going to use the *reshape* command and the ":" notation we learned earlier to create two matrices __A__ and __B__:

In [25]:
A = reshape(1:15, 3, 5)


A =

     1     4     7    10    13
     2     5     8    11    14
     3     6     9    12    15



We used the __reshape__ command above to arrange the array of numbers 1, 2,...,15 into a 3x5 matrix.

Next we'll create a new matrix __B__ which is equal to the matrix __A__ but with every element of __A__ multiplied by 2:

In [26]:
B = 2 * A


B =

     2     8    14    20    26
     4    10    16    22    28
     6    12    18    24    30



To add these two matrices:

In [27]:
A + B


ans =

     3    12    21    30    39
     6    15    24    33    42
     9    18    27    36    45



To multiply __A__ with the transpose of __B__:

In [28]:
A * B'


ans =

   670   740   810
   740   820   900
   810   900   990



You can take powers of square matrices. Let's create a square matrix __C__ equal to the upper 2x2 submatrix of A and raise this to the 2nd power, i.e. C * C:

In [29]:
C = A(1:2,1:2);
C^2   %same as C*C


ans =

     9    24
    12    33



To do elementwise operations using the matrices __A__ and __B__ use the "." notation. Here we'll do elementwise multiplication and element wise division:

In [30]:
A .* B   %this is different from A*B


ans =

     2    32    98   200   338
     8    50   128   242   392
    18    72   162   288   450



In [31]:
A ./ B   %this is different from A/B


ans =

    0.5000    0.5000    0.5000    0.5000    0.5000
    0.5000    0.5000    0.5000    0.5000    0.5000
    0.5000    0.5000    0.5000    0.5000    0.5000



Create a new matrix which is the matrix __A__ but with every element raised to the 2nd power:

In [32]:
A .^ 2   %this is different from A^2


ans =

     1    16    49   100   169
     4    25    64   121   196
     9    36    81   144   225



### Applying Functions to Matrices

You can apply functions to the matrix as a whole and the function will get applied to each element in the matrix. We apply Matlab's built-in *sin* function to __A__:

In [33]:
A


A =

     1     4     7    10    13
     2     5     8    11    14
     3     6     9    12    15



In [34]:
sin(A)


ans =

    0.8415   -0.7568    0.6570   -0.5440    0.4202
    0.9093   -0.9589    0.9894   -1.0000    0.9906
    0.1411   -0.2794    0.4121   -0.5366    0.6503



There are other useful built-in functions that can be applied to matrices. Let's consider the *sum* function:

In [35]:
sum(A)


ans =

     6    15    24    33    42



By default, you get the sum of each column (i.e. across the rows). To get the sum by row (i.e. across the columns):

In [36]:
sum(A,2)


ans =

    35
    40
    45



Here the second argument indicates the dimension to sum across; so by default, the second argument is equal to 1.

To sum up all the numbers in the matrix what would you do? You could try the following:

In [37]:
sum(sum(A))


ans =

   120



You could also do

In [38]:
sum(A(:))


ans =

   120



There are other useful functions that can be applied to matrices: min, max, mean, median, sort. Let's consider a few of these.

In [39]:
max(A)


ans =

     3     6     9    12    15



The *max* function by default returns the maximum of each column. As you can guess, to get the maximum of each row just specify the row dimension as an input to the command:

In [40]:
max(A,[],2)


ans =

    13
    14
    15



Note the use of "[ ]" in the above command which prevents Matlab from doing an elementwise max comparison. To calculate the mean by column:

In [41]:
mean(A)


ans =

     2     5     8    11    14



And calculating the mean by row:

In [42]:
mean(A,2)


ans =

     7
     8
     9



The last function we'll consider is *sort*. The default is to sort each column in ascending order:

In [43]:
result


result =

     2     2     1     0
     2     2     0     1
     1     1     3     3
     1     1     3     3



In [44]:
sort(result)


ans =

     1     1     0     0
     1     1     1     1
     2     2     3     3
     2     2     3     3



If you wanted each column sorted in descending order:

In [45]:
sort(result,'descend')


ans =

     2     2     3     3
     2     2     3     3
     1     1     1     1
     1     1     0     0



And to sort each row:

In [46]:
sort(result,2)


ans =

     0     1     2     2
     0     1     2     2
     1     1     3     3
     1     1     3     3



A useful thing may be to sort only by a single column (i.e. the third column). For this you can use the *sortrows* functions and specify the column to sort by:

In [47]:
result


result =

     2     2     1     0
     2     2     0     1
     1     1     3     3
     1     1     3     3



In [48]:
sortrows(result,3)


ans =

     2     2     0     1
     2     2     1     0
     1     1     3     3
     1     1     3     3



# Exercise 2.

1. Create a 4x4 random matrix called __mymat__ using the *rand* function.
2. Change every element of the second row to be equal to three.
2. Add two to every element of the modified matrix and than take the transpose and assign the result to a new matrix called __mymat_new__.
3. Find the maximum of each column of __mymat_new__.

In this lesson you learned:
* How to create and modify matrices.
* How to index into matrices.
* Matrix operations.
* Applying functions to matrices.