# III. Introduction to Matrices

Let's create a simple 4x4 matrix and check its size:

In [2]:
A = [1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16]


A =

     1     2     3     4
     5     6     7     8
     9    10    11    12
    13    14    15    16



In [3]:
size(A)


ans =

     4     4



If you wanted the diagonal elements of A you would use the *diag* command:

In [4]:
diag(A)


ans =

     1
     6
    11
    16



Matlab has built-in commands for creating many commonly used matrices. We can create a 2x2 matrix of zeros:

In [5]:
zeros(2)


ans =

     0     0
     0     0



Or a 3x4 matrix of ones:

In [6]:
ones(3,4)


ans =

     1     1     1     1
     1     1     1     1
     1     1     1     1



To create the identity matrix use the *eye* command:

In [7]:
eye(4)


ans =

     1     0     0     0
     0     1     0     0
     0     0     1     0
     0     0     0     1



To create a diagonal matrix:

In [8]:
diag([1 3 5])


ans =

     1     0     0
     0     3     0
     0     0     5



A random 3x3matrix where each element is uniformly distributed between 0 and 1:

In [9]:
rand(3)


ans =

    0.8147    0.9134    0.2785
    0.9058    0.6324    0.5469
    0.1270    0.0975    0.9575



A common operation is to create matrices using other matrices. Matrices can be constructed in block form. Here we create a matrix __result__ using the matrices __B__, __C__, __D__, and __E__:

In [10]:
B = [2 2;2 2];
C = eye(2);
D = ones(2);
E = [3 3;3 3];
result = [B C; D E]


result =

     2     2     1     0
     2     2     0     1
     1     1     3     3
     1     1     3     3



The *repmat* function is very useful Matlab built-in used to construct tiled block matrices.

In [11]:
repmat(result,3,2)


ans =

     2     2     1     0     2     2     1     0
     2     2     0     1     2     2     0     1
     1     1     3     3     1     1     3     3
     1     1     3     3     1     1     3     3
     2     2     1     0     2     2     1     0
     2     2     0     1     2     2     0     1
     1     1     3     3     1     1     3     3
     1     1     3     3     1     1     3     3
     2     2     1     0     2     2     1     0
     2     2     0     1     2     2     0     1
     1     1     3     3     1     1     3     3
     1     1     3     3     1     1     3     3



In [12]:
help repmat

 REPMAT Replicate and tile an array.
    B = REPMAT(A,M,N) or B = REPMAT(A,[M,N]) creates a large matrix B 
    consisting of an M-by-N tiling of copies of A. If A is a matrix, 
    the size of B is [size(A,1)*M, size(A,2)*N].
 
    B = REPMAT(A,N) creates an N-by-N tiling.  
    
    B = REPMAT(A,P1,P2,...,Pn) or B = REPMAT(A,[P1,P2,...,Pn]) tiles the array 
    A to produce an n-dimensional array B composed of copies of A. The size 
    of B is [size(A,1)*P1, size(A,2)*P2, ..., size(A,n)*Pn].
    If A is m-dimensional with m > n, an m-dimensional array B is returned.
    In this case, the size of B is [size(A,1)*P1, size(A,2)*P2, ..., 
    size(A,n)*Pn, size(A, n+1), ..., size(A, m)].
 
    REPMAT(A,M,N) when A is a scalar is commonly used to produce an M-by-N
    matrix filled with A's value and having A's CLASS. For certain values,
    you may achieve the same results using other functions. Namely,
       REPMAT(NAN,M,N)           is the same as   NAN(M,N)
       REPMAT(SINGLE(INF)

A common need is the ability to index into a matrix and extract parts of the matrix (i.e. a submatrix). In Matlab indexing into a matrix is accomplished using parentheses. Let's consider our matrix __result__:

In [13]:
result


result =

     2     2     1     0
     2     2     0     1
     1     1     3     3
     1     1     3     3



Suppose we want to extract the upper left matrix of 2s and assign it to a new variable called __subupper__. Indexing starts at 1 and we'd simply specify the range of rows and columns desired. Here we want rows 1 through 2 and columns 1 through 2:

In [14]:
subupper = result(1:2, 1:2)


subupper =

     2     2
     2     2



If we wanted the middle two rows but only columns 1 through 3:

In [15]:
midrows = result(2:3, 1:3)


midrows =

     2     2     0
     1     1     3



What if we wanted the first two columns?

In [16]:
firstcols = result(1:4,1:2)


firstcols =

     2     2
     2     2
     1     1
     1     1



Another way to do the same thing using the "end" keyword:

In [17]:
firstcols = result(1:end, 1:2)


firstcols =

     2     2
     2     2
     1     1
     1     1



You can use the colon ":" notation to get the entire range of the dimension of interest:

In [18]:
result(:,3)


ans =

     1
     0
     3
     3



Above we asked for all the rows and just the third column of the matrix __result__.

You can be specific about what you want. What if you wanted just the corner numbers?

In [19]:
result([1 end], [1 end])


ans =

     2     0
     1     3



We saw the ":" notation before and how it's used to specify a range of numbers, i.e. 1:3. This syntax is often used in Matlab to create vectors. __begin:stride:end__ is the general syntax and by default __stride__ as a value of 1 (i.e. if not specified):

In [20]:
a=1:10


a =

     1     2     3     4     5     6     7     8     9    10



We can find the length of _a_ using the *length* command:

In [22]:
length(a)


ans =

    10



The length of the vector will be equal to the number of elements in it.

If you wanted to go from 3 to 8 in increments of 0.5 you can specify a stride of 0.5:

In [23]:
b = 3:0.5:8


b =

  Columns 1 through 7

    3.0000    3.5000    4.0000    4.5000    5.0000    5.5000    6.0000

  Columns 8 through 11

    6.5000    7.0000    7.5000    8.0000



Or if you wanted a sequence to start at -20 and go to 1 in increments of 1.3:

In [24]:
c = -20:1.3:1


c =

  Columns 1 through 7

  -20.0000  -18.7000  -17.4000  -16.1000  -14.8000  -13.5000  -12.2000

  Columns 8 through 14

  -10.9000   -9.6000   -8.3000   -7.0000   -5.7000   -4.4000   -3.1000

  Columns 15 through 17

   -1.8000   -0.5000    0.8000



Notice Matlab could not reach all the way to one using the specified increment of 1.3; so it went up in increments of 1.3 until it reached as close to 1 without going beyond 1.

The linspace command will create n equally spaced points between a and b, *linspace(__a__,__b__,__n__)*:

In [25]:
linspace(1.5,5.5,10)


ans =

  Columns 1 through 7

    1.5000    1.9444    2.3889    2.8333    3.2778    3.7222    4.1667

  Columns 8 through 10

    4.6111    5.0556    5.5000



Before moving on to operations with matrices I'll mention that you can create multidimenional arrays (sometimes referred to as tensors) in Matlab as well. For example, the following creates a 4x3x3 random matrix:

In [26]:
F = randn(4,3,3)


F(:,:,1) =

    2.7694   -0.0631    1.4897
   -1.3499    0.7147    1.4090
    3.0349   -0.2050    1.4172
    0.7254   -0.1241    0.6715


F(:,:,2) =

   -1.2075    1.0347   -0.7873
    0.7172    0.7269    0.8884
    1.6302   -0.3034   -1.1471
    0.4889    0.2939   -1.0689


F(:,:,3) =

   -0.8095   -0.7549   -0.2414
   -2.9443    1.3703    0.3192
    1.4384   -1.7115    0.3129
    0.3252   -0.1022   -0.8649



You can think of this as 3 "layers" of individual 4x3 matrices (i.e. a cube), i.e. each layer is a 4x3 matrics. You can index into multidementional arrays as well:

In [27]:
G = F(1:2,2:3,:)


G(:,:,1) =

   -0.0631    1.4897
    0.7147    1.4090


G(:,:,2) =

    1.0347   -0.7873
    0.7269    0.8884


G(:,:,3) =

   -0.7549   -0.2414
    1.3703    0.3192



Above, we specified columns 2 through 3 of the first two rows from all the layers.

As expected you can do common matrix operations in Matlab. I'm going to use the *reshape* command and the ":" notation we learned earlier to create two matrices __A__ and __B__:

In [28]:
A = reshape(1:15,3,5)


A =

     1     4     7    10    13
     2     5     8    11    14
     3     6     9    12    15



Next we'll create a new matrix __B__ which is equal to the matrix __A__ but with every element of __A__ multiplied by 2:

In [29]:
B = 2 * A


B =

     2     8    14    20    26
     4    10    16    22    28
     6    12    18    24    30



To add these two matrices:

In [30]:
A + B


ans =

     3    12    21    30    39
     6    15    24    33    42
     9    18    27    36    45



To multiply the __A__ with the transpose of __B__:

In [31]:
A * B'


ans =

   670   740   810
   740   820   900
   810   900   990



You can take powers of square matrices. Let's create a square matrix __C__ equal to the upper 2x2 submatrix of A and raise this to the 2nd power, i.e. C * C:

In [32]:
C = A(1:2,1:2);
C^2


ans =

     9    24
    12    33



In [33]:
C * C


ans =

     9    24
    12    33



To do element wise operations using the matrices __A__ and __B__ use the "." notation. Here we'll do element wise multiplication and element wise division:

In [34]:
A .* B


ans =

     2    32    98   200   338
     8    50   128   242   392
    18    72   162   288   450



In [35]:
A ./ B


ans =

    0.5000    0.5000    0.5000    0.5000    0.5000
    0.5000    0.5000    0.5000    0.5000    0.5000
    0.5000    0.5000    0.5000    0.5000    0.5000



Create a new matrix which is the matrix __A__ but with every element raised to the 2nd power:

In [36]:
A.^2


ans =

     1    16    49   100   169
     4    25    64   121   196
     9    36    81   144   225



You can apply functions to the matrix as a whole and the function will get applied to each element in the matrix. We apply Matlab's built-in *sin* function to __A__:

In [37]:
sin(A)


ans =

    0.8415   -0.7568    0.6570   -0.5440    0.4202
    0.9093   -0.9589    0.9894   -1.0000    0.9906
    0.1411   -0.2794    0.4121   -0.5366    0.6503



There are other useful built-in functions that can be applied to matrices. Let's consider the *sum* function:

In [40]:
A


A =

     1     4     7    10    13
     2     5     8    11    14
     3     6     9    12    15



In [41]:
sum(A)


ans =

     6    15    24    33    42



By default, you get the sum of each column (i.e. across the rows). To get the sum by row (i.e. across the columns):

In [42]:
sum(A,2)


ans =

    35
    40
    45



Here the second argument indicates the dimension to sum across; so by default, the second argument is equal to 1.

To sum up all the numbers in the matrix what would you do? You could try the following:

In [44]:
sum(sum(A))


ans =

   120

