# III. Working with Matrices

One of Matlab's strenths is numerical computation and doing matrix operations. It's easy to create and manipulate matrices in Matlab.

Let's create a simple 4x4 matrix and check its size:

In [1]:
A = [1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16]


A =

     1     2     3     4
     5     6     7     8
     9    10    11    12
    13    14    15    16



In [14]:
size(A)


ans =

     4     4



We can create a 2x2 matrix of zeros:

In [3]:
zeros(2)


ans =

     0     0
     0     0



Or a 3x4 matrix of ones:

In [4]:
ones(3,4)


ans =

     1     1     1     1
     1     1     1     1
     1     1     1     1



To create the identity matrix use the eye command:

In [5]:
eye(4)


ans =

     1     0     0     0
     0     1     0     0
     0     0     1     0
     0     0     0     1



A random matrix where each element is uniformly distributed between 0 and 1:

In [6]:
rand(3)


ans =

    0.8147    0.9134    0.2785
    0.9058    0.6324    0.5469
    0.1270    0.0975    0.9575



In [8]:
A


A =

     1     2     3     4
     5     6     7     8
     9    10    11    12
    13    14    15    16



A common operation is to create matrices using other matrices. Matrices can be constructed in block form. Here we create a matrix "result" using the matrices "B", "C", "D", and "E":

In [11]:
B = [2 2;2 2];
C = eye(2);
D = ones(2);
E = [3 3;3 3];
result = [B C; D E]


result =

     2     2     1     0
     2     2     0     1
     1     1     3     3
     1     1     3     3



The repmat function is very useful Matlab built-in used to construct tiled block matrices.

In [12]:
repmat(result,3,2)


ans =

     2     2     1     0     2     2     1     0
     2     2     0     1     2     2     0     1
     1     1     3     3     1     1     3     3
     1     1     3     3     1     1     3     3
     2     2     1     0     2     2     1     0
     2     2     0     1     2     2     0     1
     1     1     3     3     1     1     3     3
     1     1     3     3     1     1     3     3
     2     2     1     0     2     2     1     0
     2     2     0     1     2     2     0     1
     1     1     3     3     1     1     3     3
     1     1     3     3     1     1     3     3



In [13]:
help repmat

 REPMAT Replicate and tile an array.
    B = REPMAT(A,M,N) or B = REPMAT(A,[M,N]) creates a large matrix B 
    consisting of an M-by-N tiling of copies of A. If A is a matrix, 
    the size of B is [size(A,1)*M, size(A,2)*N].
 
    B = REPMAT(A,N) creates an N-by-N tiling.  
    
    B = REPMAT(A,P1,P2,...,Pn) or B = REPMAT(A,[P1,P2,...,Pn]) tiles the array 
    A to produce an n-dimensional array B composed of copies of A. The size 
    of B is [size(A,1)*P1, size(A,2)*P2, ..., size(A,n)*Pn].
    If A is m-dimensional with m > n, an m-dimensional array B is returned.
    In this case, the size of B is [size(A,1)*P1, size(A,2)*P2, ..., 
    size(A,n)*Pn, size(A, n+1), ..., size(A, m)].
 
    REPMAT(A,M,N) when A is a scalar is commonly used to produce an M-by-N
    matrix filled with A's value and having A's CLASS. For certain values,
    you may achieve the same results using other functions. Namely,
       REPMAT(NAN,M,N)           is the same as   NAN(M,N)
       REPMAT(SINGLE(INF)