# IV. Basic Programming Constructs

In this notebook we'll go over some basic logical and comparison operators and control flow statements in Matlab. These are common programming constructs you'll likely be using when writing your Matlab code.

### Logical and Relational Operators

To get started you'll want to be familiar with Matlab's boolean types: __true__ and __false__

In [1]:
a = true


a =

  logical

   1



In [2]:
b = false


b =

  logical

   0



The logical type __true__ numerically takes a value of 1; __false__ takes a value of 0.

These logical types are the basis for doing logical operations. Matlab has the usual logical operators available:

* & logical and
* && logical and with short-circuiting
* | logical or
* || logical or with short short-circuiting
* ~ logical not

Note. The short-circuit operations work on scalars only.

Matlab also has the traditional relational operators:

* == equal
* ~= not equal
* < less than
* \> greater than
* <= less than or equal
* \>= greater than or equal

Let's look at some examples of using these operators.

Create two variables __a__ and __b__:

In [3]:
a = 2; b = 3;

Check if a > b and assign the result to a variable called __c__:

In [4]:
c = a > b


c =

  logical

   0



Note __c__ is a logical type. Specifically, __c__ is __false__ since __a__ is not greater than __b__.

Let's create a variable __d__ equal to 29 and use it in a boolean expression:

In [5]:
d = 29;

In [6]:
e = (a > b) && (d >= 20)


e =

  logical

   0



Above we asked if __a__ is greater than __b__ AND is __d__ greater than or equal to 20. One of the statements is false, so the AND of them will be a logical false.

Now we ask if a is greater than b OR if d is greater than or equal to 20. The second statement is true (i.e. 29 $\ge$ 20) so __f__ will be true since for __f__ to be true only one of the statements neeeds to be true.

In [7]:
f = (d >= 20) || (a > b)


f =

  logical

   1



The logical __not__ operator will reverse a logical type. Here "not __f__" will return a logical false since __f__ is a logical true.

In [8]:
~f


ans =

  logical

   0



Matlab provides some logical operator functions for arrays such as __any__ and __all__:
* __any__ true if any element of the vector is nonzero
* __all__ true if all elements of the vector are nonzero

Let's create a vector z:

In [9]:
z = [0 0 0 -3 4 0 0 10 0 -99]


z =

     0     0     0    -3     4     0     0    10     0   -99



In [10]:
any(z)


ans =

  logical

   1



In [11]:
all(z)


ans =

  logical

   0



A useful function is __find__ which returns indices that correspond to nonzero elements of the array.

In [12]:
z


z =

     0     0     0    -3     4     0     0    10     0   -99



In [13]:
find(z)


ans =

     4     5     8    10



You can use __find__ to return just the nonzero elements of __z__:

In [14]:
z(find(z))


ans =

    -3     4    10   -99



Let's now apply some of what we've learned to matrices.

In [15]:
A = [2 -32 9; 66 2 -16]


A =

     2   -32     9
    66     2   -16



In [16]:
B = [1 2 -2; 12 43 -88]


B =

     1     2    -2
    12    43   -88



The following returns a logical array of whether an element of A is greater than zero.

In [17]:
A > 0


ans =

  2x3 logical array

   1   0   1
   1   1   0



To get a logical array that indicates if the element of B is less than zero.

In [18]:
B < 0


ans =

  2x3 logical array

   0   0   1
   0   0   1



You can do logical operations using logical arrays (can not use short-circuiting). The logical operation is done element-wise.

In [19]:
(A > 0) & (B < 0)


ans =

  2x3 logical array

   0   0   1
   0   0   0



To return a logical array indicating elements of A that are greater than B.

In [20]:
A > B


ans =

  2x3 logical array

   1   0   1
   1   0   1



To get a list of the elements in A that are greater than their corresponding elements in B.

In [21]:
A(A>B)


ans =

     2
    66
     9
   -16



### Programming Flows

Let's look at some basic constructs for controlling the flow of you program: __if__ statement, __for__ loop, __while__ loop, and the __switch__ statement.

The basic structure of the __if__ statment is: <br />

__if__ *expression* <br />
&nbsp;&nbsp;&nbsp;statements <br />
__end__ <br />

The *expression* should evaluate to true or false and determines whether or not the statements inside the if block get executed.

In [22]:
a = 2; b = 3;

if (a < b)
    disp('a is less than b')
end

a is less than b


In [23]:
a = 20; b = 10;

if (a < b)
    disp('a is less than b')
else
    disp('a is greater than or equal to b')
end

a is greater than or equal to b


In [24]:
a = 20; b = 20;

if (a < b)
    disp('a is less than b')
elseif (a > b)
    disp('a is greater than b')
else
    disp('a is equal to b')
end

a is equal to b


In [25]:
a = 20; b = 2; d = 15;

if (a > b)
    disp('a is greater than b')
elseif (d > 10)
    disp('d is greater than 10')
else
    disp('a is neither greater than b nor is d greater than 10')
end

a is greater than b


The last expression shows that once a condition is true, the entire __if__ block is exited, i.e. the remaining conditions are not checked.

The for loop is a construct that allows you to iterate over a block of code. It's basic structure is

__for__ *index* = *expression*<br />
&nbsp;&nbsp;&nbsp;statements <br />
__end__ <br />

*index* is referred to as the index variable.

You can use a for loop to add up the first 10 integers:

In [26]:
sum = 0;
N = 10;

for i = 1:N
    sum = sum + i;
end

sum


sum =

    55



The __for__ loop is also useful for indexing into a vector or matrix and performing calculations:

In [27]:
% allocate a vector zeros

v = zeros(10,1)'


v =

     0     0     0     0     0     0     0     0     0     0



In [28]:
%now fill the vector with some values

lv = length(v);

for j = 1:(lv - 1)
    v(j+1) = 0.4*v(j) + randn;
end
v


v =

  Columns 1 through 7

         0    0.5377    2.0490   -1.4393    0.2865    0.4334   -1.1343

  Columns 8 through 10

   -0.8873   -0.0123    3.5735



You can use the __break__ keyword to break out of for loops if some condition is met. Below we break out of the loop as soon as the value of sum is greater than or equal to 70.

In [29]:
sum = 0;
N = 100;

for i = 1:N
    sum = sum + i;
    if sum >=70
        break
    end
end
sum


sum =

    78



The while loop is another construct that allows you to repeatedly execute a block of code. Instead of doing so for some 
fixed number or iterations, it does so while some condition is met (i.e. is true). It's basic structure is

__while__ *expression*<br />
&nbsp;&nbsp;&nbsp;statements <br />
__end__ <br />

To prevent the loop from running endlessly ("infinite loop") you'll want to be sure that the *expression* that the while loop depends on becomes false at some point. 

In the example below we use a while loop to calculate the factorial of 6.

In [30]:
n = 6; 
fact = n;

while (n > 1)
    fact = fact * (n-1);
    n = n-1;
end
fact


fact =

   720



Note Matlab has a built-in factorial __function__ you can use to calculate the factorial. The above while loop was just for illustrative purposes. You wouldn't want to use it to calculate the factorial in your code.

In [31]:
factorial(6)


ans =

   720



The last Matlab programming construct we'll discuss is the **switch** statement which allows you to execute one of several groups of statements. The basic structure is

__switch__ *switch_expression*<br />
&nbsp;&nbsp;&nbsp;__case__ *case_expression*<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;statements<br />
&nbsp;&nbsp;&nbsp;__case__ *case_expression*<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;statements<br />
&nbsp;&nbsp;&nbsp;__otherwise__<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;statements<br />
end

In [ ]:
a = 2; b = 3;
operator = '*';

switch operator
    case '+'
        result = a + b;
    case '-'
        result = a - b;
    case '*'
        result = a * b;
    case '/'
        result = a/b;
    otherwise
        result = 'operation not defined';
end
result

As soon as a case expression is true, its statement is executed and the switch block is exited.

# Exercise 3.

1. Create a 1x20 random vector called __myvec__ using the *randn* function.
2. Use if statements within a for loop to change the elements in __myvec__ so that a negative element is changed to -1, a positive element is changed to one.

In this lesson you learned:
* The basic logical types true and false.
* How to use logical and comparison operators on scalars, vectors, and matrices.
* Using Matlab functions to do matrix subsetting.
* Control flow structures: if statement, for loop, while loop, switch statement.