# IV. Basic Programming Constructs

In this notebook we'll go over some basic logical and comparison operators and control flow statements in Matlab. These are common programming constructs used in general purpose code.

To get started you'll want to be familiar with Matlab's boolean types: __true__ and __false__

In [1]:
a = true


a =

  logical

   1



In [2]:
b = false


b =

  logical

   0



The logical type __true__ numerically takes a value of 1; __false__ takes a value of 0.

These logical types are the basis for doing logical operations. Matlab has the usual logical operators available:

* & logical and
* && logical and with short-circuiting
* | logical or
* || logical or with short short-circuiting
* ~ logical not

Note. The short-circuit operations work on scalars only.

Matlab also has the traditional relational operators:

* == equal
* ~= not equal
* < less than
* \> greater than
* <= less than or equal
* \>= greater than or equal

At this point, we have enough to get started. Let's begin with looking at scalars and then we'll work our way up to vectors and matrices:

Create two variables __a__ and __b__:

In [1]:
a=2;b=3;

Check if a > b and assign the result to a variable called __c__:

In [2]:
c = a > b


c =

  logical

   0



Note __c__ is a logical type. Specifically, __c__ is __false__ since __a__ is not greater than __b__.

Let's create a variable __d__ equal to 29 and use it in a boolean expression:

In [3]:
d=29;

In [4]:
e = (a > b) && (d >= 20)


e =

  logical

   0



Above we asked if __a__ is greater than __b__ AND is __d__ greater than or equal to 20. Both statements are false, so the AND of them will be a logical false.

Now we ask if a is greater than b OR if d is greater than or equal to 20. The second statement is true (i.e. 29 > 20) so __f__ will be true since for __f__ to be true only of the statements neeeds to be true.

In [5]:
f = (a > b) || (d >= 20)


f =

  logical

   1



The logical __not__ operator will reverse a logical type. Here "not __f__" will return a logical false since __f__ is a logical true.

In [6]:
~f


ans =

  logical

   0



Next we create some vectors and apply relational operators to them.

In [11]:
v = [1 8 -3 4.2]


v =

    1.0000    8.0000   -3.0000    4.2000



In [12]:
w = [-9 0.75 99 0]


w =

   -9.0000    0.7500   99.0000         0



The following checks if every element of __v__ is greater than zero and returns true or false for each elementwise comparision:

In [13]:
v > 0


ans =

  1x4 logical array

   1   1   0   1



Similarly, this checks if every element of __w__ is less than zero returning a logical array as well.

In [14]:
w < 0


ans =

  1x4 logical array

   1   0   0   0



If you wanted the elements of __v__ that are greater than zero you can use subsetting in conjuction with a relational operator.

In [15]:
v(v>0)


ans =

    1.0000    8.0000    4.2000



The next cell does an elementwise logical AND operation between the two logical arrays returned above.

In [11]:
v > 0 & w < 0


ans =

  1x4 logical array

   1   0   0   0



And the following does the elementwise logical OR operation using the same two logical arrays.

In [12]:
v > 0 | w > 0


ans =

  1x4 logical array

   1   1   1   1



Matlab provides some logical operator functions for arrays such as __xor__, __any__, and __all__:
* __xor__ logical exclusive or
* __any__ true if any element of the vetor is nonzero
* __all__ true if all elements of the vector are nonzero

In [2]:
z = zeros(1,10) + [0 0 0 -3 4 0 0 10 0 -99]


z =

     0     0     0    -3     4     0     0    10     0   -99



In [2]:
any(z)


ans =

  logical

   1



In [3]:
all(z)


ans =

  logical

   0



A useful function is __find__ which returns indices that correspond to nonzero elements of the array.

In [16]:
find(z)


ans =

     4     5     8    10



If you wanted just th nonzero elements of __z__ you can do the following subsetting operations:

In [18]:
z(find(z))


ans =

    -3     4    10   -99



Let's apply some of what we've learned to matrices.

In [6]:
A = [2 -32 9; 66 2 -16]; B = [1 2 -2; 12 43 -88];

The following returns a logical array of whether an element of A is greater than zero.

In [8]:
A > 0


ans =

  2x3 logical array

   1   0   1
   1   1   0



To return a logical array indicating elements of A that are greater than B.

In [11]:
A > B


ans =

  2x3 logical array

   1   0   1
   1   0   1



To get a list of the elements in A that are greater than their corresponding elements in B.

In [13]:
A(A>B)


ans =

     2
    66
     9
   -16



You can use __find__ to find the indices of the elements in A that are greater than their corresponding elements in B.

In [16]:
find(A>B)


ans =

     5
     6



What if you wanted to set these elements in A equal to -1?

In [ ]:
A(find(A>B)) = -1


A =

    -1   -32    -1
    -1     2    -1

